### ISSUE TITLE
SQL Error on load

### ISSUE THREAD

**Issue by k9sniffer** [cmgriffing/orderly#33]
**Edited by repo owner**

Several users have reported having this issue. 

Originally it was reproducible due to a timing issue combined with coi-serviceworker. We have since redployed the project to Render instead of GitHub pages to avoid the need for coi-serviceworker.

Some users still reported the error.

The specific error has been about  the "books" table not existing. So far the main cause seems to be related to private or incognito mode.

> First Report from k9sniffer:
> 
> When I go to select the model I want to use it fails to allow me to select a model before giving me a sql error. Or upon slecting a model it gives an sql error Using Iphone 14 pro max
> 
> See attached video
> 
> https://github.com/cmgriffing/orderly/assets/45606148/ab0c4d2d-c6cb-41b4-8ae1-507e76537512
> 
>

**Comment by JanGanaCode** [comment]
Using "**Never Remember History**" in Firefox causes this issue

**Comment by cmgriffing** [comment]
I believe we have recently solved this using an Error page that informs the user that this will not work in incognito mode. Feel free to keep adding to this if you see new cases in which this bug can happen.
